### ISSUE TITLE
可以双屏输出吗

### ISSUE THREAD

**Issue by lizhian** [youngle316/ASRock-Z370M-ITX-AC#6]
主板dp输出4k,hdmi输出1080p(能2k,4k更好)

**Comment by youngle316** [comment]
没有双屏，以前的1080p的送人了。主板dp可以4K，hdmi可以1080p。这个主板的hdmi不支持4K的

**Comment by hanxi2719** [comment]
主板的双HDMI支持4K的但是只是30hz，不支持4K 60hz，dp支持4K 60hz发自我的iPhone------------------ 原始邮件 ------------------发件人: YangLeLe  <notifications@github.com>发送时间: 2019年12月17日 22:02收件人: youngle316/ASRock-Z370M-ITX-AC <ASRock-Z370M-ITX-AC@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[youngle316/ASRock-Z370M-ITX-AC] 可以双屏输出吗 (#6)没有双屏，以前的1080p的送人了。主板dp可以4K，hdmi可以1080p。这个主板的hdmi不支持4K的

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/youngle316/ASRock-Z370M-ITX-AC/issues/6?email_source=notifications\u0026email_token=AIOQ66N4ZAXFNEH3JTNITGDQZDLXDA5CNFSM4J3UPBYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHCOWYQ#issuecomment-566553442",
"url": "https://github.com/youngle316/ASRock-Z370M-ITX-AC/issues/6?email_source=notifications\u0026email_token=AIOQ66N4ZAXFNEH3JTNITGDQZDLXDA5CNFSM4J3UPBYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHCOWYQ#issuecomment-566553442",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by lizhian** [comment]
噢~谢解答
